# Generated by Django 3.2.3 on 2021-05-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_addblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='addblog',
            name='hotel_Main_Img',
            field=models.ImageField(default=1, upload_to='img/images/'),
            preserve_default=False,
        ),
    ]
