# Generated by Django 3.2.3 on 2021-05-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_addblog_hotel_main_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addblog',
            old_name='hotel_Main_Img',
            new_name='Img',
        ),
    ]
