# Generated by Django 3.2.3 on 2021-05-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0006_addblog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='Img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
