# Generated by Django 3.2.3 on 2021-05-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0010_alter_addblog_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addblog',
            old_name='Title',
            new_name='Project_name',
        ),
        migrations.RemoveField(
            model_name='addblog',
            name='email',
        ),
        migrations.AddField(
            model_name='addblog',
            name='P_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addblog',
            name='Decri',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addblog',
            name='Img',
            field=models.ImageField(upload_to='add_images'),
        ),
    ]
