# Generated by Django 3.2.3 on 2021-05-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0011_auto_20210529_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='author',
            field=models.CharField(max_length=225),
        ),
    ]
