# Generated by Django 3.2.3 on 2021-05-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0016_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Author',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='header',
            field=models.CharField(max_length=500),
        ),
    ]
