# Generated by Django 3.2.3 on 2021-05-31 14:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0019_auto_20210531_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='content1',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
