# Generated by Django 3.2.3 on 2021-06-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0020_notes_content1'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproject',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('Decri', models.CharField(max_length=255)),
                ('p_url', models.CharField(max_length=255)),
                ('Img', models.ImageField(upload_to='add_images')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
