# Generated by Django 3.2.3 on 2021-06-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0021_addproject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='blog',
        ),
        migrations.RenameModel(
            old_name='addproject',
            new_name='project',
        ),
    ]
