# Generated by Django 3.2.3 on 2021-06-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0022_auto_20210601_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content1',
        ),
    ]
