# Generated by Django 3.2.3 on 2021-06-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0023_remove_blog_content1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=500)),
                ('document', models.ImageField(upload_to='add_images')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='addblog',
        ),
    ]
