# Generated by Django 3.2.3 on 2021-06-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0024_auto_20210601_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='document_img',
        ),
    ]
